<?php
	$base_url = "https://sndipn616.github.io/"; 
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
		<title><<MODIFY>>Sandipan Mandal</title>
		<link rel="stylesheet" type="text/css" href="css/style-moz.css">
		<!--[if IE]> <link rel="stylesheet" type="text/css" href="css/style-ie.css"> <![endif]-->
	</head>
	<body>
		<center>
			<table class="main" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td>
						<div class="container">
							<table class="t_data" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td class="t_left" rowspan="2" valign="top">
